from .nuclei import infer_NUCLEI
from .soma import infer_SOMA
from .cytosol import infer_CYTOSOL
from .lysosomes import infer_LYSOSOMES
from .mitochondria import infer_MITOCHONDRIA
from .golgi import infer_GOLGI
from .peroxisomes import infer_PEROXISOME
from .er import infer_ENDOPLASMIC_RETICULUM
from .lipid import infer_LIPID_DROPLET
